#!/bin/bash
# Build the image.

set -e
now=`date +%Y-%m-%d--%H%M%S`

# Short term hack until aarch64 is supported.
export PORT_ARCH=armv7hl

# Adapt the kickstart file.
HA_REPO="repo --name=adaptation0-$DEVICE-@RELEASE@"
KS="Jolla-@RELEASE@-$DEVICE-@ARCH@.ks"
sed -e "s|^$HA_REPO.*$|$HA_REPO --baseurl=file://$ANDROID_ROOT/droid-local-repo/$DEVICE|" $ANDROID_ROOT/hybris/droid-configs/installroot/usr/share/kickstarts/$KS > tmp/$KS

# Prepare patterns
hybris/droid-configs/droid-configs-device/helpers/process_patterns.sh

# Build the image
RELEASE=2.1.0.10
# EXTRA_NAME adds your custom tag. It doesn't support '.' dots in it!
EXTRA_NAME=-ksandom-$now
sudo mic create fs --arch $PORT_ARCH \
--debug \
--tokenmap=ARCH:$PORT_ARCH,RELEASE:$RELEASE,EXTRA_NAME:$EXTRA_NAME \
--record-pkgs=name,url \
--outdir=sfe-$DEVICE-$RELEASE$EXTRA_NAME \
--pack-to=sfe-$DEVICE-$RELEASE$EXTRA_NAME.tar.bz2 \
$ANDROID_ROOT/tmp/Jolla-@RELEASE@-$DEVICE-@ARCH@.ks

# Copy non sailfish images into the release folder incase they may be useful later.
cp out/target/product/$DEVICE/*img sfe-$DEVICE-$RELEASE$EXTRA_NAME
